### ISSUE TITLE
数据缺失

### ISSUE THREAD

**Issue by shixianqin** [wecatch/china_regions#10]
广东东莞，广东中山，海南三沙，等地的区县数据不存在

**Comment by ChaunceyHuo** [comment]
你好，感谢提醒，这是分享的文件，可能有更新问题。不过我刚查询了一下，我国暂有五个不设市辖区的城市，又称为直筒子市，分别为广东省东莞市和中山市，海南省的三沙市和儋州市、甘肃省的嘉峪关市。这五个城市直接辖属乡镇、街道等。
        而统计用区划代码和城乡划分代码所涉及的数据，是国家统计局开展统计调查所涉及的区划范围，未包括我国台湾省、香港特别行政区、澳门特别行政区。统计用区划代码和城乡划分代码包括12位统计用区划代码、2位城乡属性代码和3位城乡分类代码。其中，城乡属性代码主要用于数据质量控制，暂未公布。
