### ISSUE TITLE
数据不全

### ISSUE THREAD

**Issue by newpanjing** [wecatch/china_regions#12]
没有香港澳门台湾钓鱼岛，差评

**Comment by jaybowong** [comment]
@newpanjing  

https://github.com/wecatch/china_regions/blob/0817421f647ca11abb4c5bca785097094f66f56f/js/province_object.js#L126-L137

**Comment by emonZan** [comment]
明明就有啊

**Comment by liuzhebaba** [comment]
没有香港，台湾，澳门下面的城市和地区，这个过分了
