### ISSUE TITLE
失效了，兄嘚！~

### ISSUE THREAD

**Issue by HaoTong93** [wecatch/china_regions#13]
失效了，兄嘚！~

**Comment by yizhi108** [comment]
请注意啊。。。真的失效了。。

**Comment by zhyq0826** [comment]
@yizhi108 你说的失效能更具体一点只出问题么

**Comment by yizhi108** [comment]
@zhyq0826  国标链接失效了。

**Comment by peakandyuri** [comment]
国标页面执行pull.js的代码，保存的文件没有内容

**Comment by xsharp** [comment]
> @yizhi108 你说的失效能更具体一点只出问题么

比如 130181 开头的数据没有：

http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/13/01/130181.html

**Comment by pdslly** [comment]
老哥 失效了  执行拿到的是空数组TnT
