### ISSUE TITLE
地区的命名写错了 是county

### ISSUE THREAD

**Issue by hui6xin** [wecatch/china_regions#14]
库里面写的是country，郡，县 应该是county

**Comment by zhyq0826** [comment]
@hui6xin 这里面对应文件的名称是根据国家统计局的分类写的，主要是为了方便爬虫能和相应的数据对应起来，你可以根据自己的需要改成你需要的即可，数据对应的国家行政级别顺序是:province-> city --> country --> town --> village，对应的是:省->市(市辖区)->县(区、市)->镇(街道)->村(居委会)
