### ISSUE TITLE
有没有整一个的json

### ISSUE THREAD

**Issue by chinavane** [wecatch/china_regions#2]
省、市、区，用children的方式进行嵌套的。不知道有没？

**Comment by zhyq0826** [comment]
@chinavane  全部数据放到一个 json 文件很大，数据都在，可以按需组合

**Comment by jbts6** [comment]
json有了就可以随意组合了

**Comment by wy1024** [comment]
我整理了一下：

https://github.com/wy1024/World_Regions/blob/master/China.json
