### ISSUE TITLE
增加东莞中山儋州

### ISSUE THREAD

**Issue by dongliang0201** [wecatch/china_regions#20]
INSERT INTO country  VALUES ('3283', '东城街道办事处', '441900003000', '441900000000');
INSERT INTO country  VALUES ('3284', '南城街道办事处', '441900004000', '441900000000');
INSERT INTO country  VALUES ('3285', '万江街道办事处', '441900005000', '441900000000');
INSERT INTO country  VALUES ('3286', '莞城街道办事处', '441900006000', '441900000000');
INSERT INTO country  VALUES ('3287', '石碣镇', '441900101000', '441900000000');
INSERT INTO country  VALUES ('3288', '石龙镇', '441900102000', '441900000000');
INSERT INTO country  VALUES ('3289', '茶山镇', '441900103000', '441900000000');
INSERT INTO country  VALUES ('3290', '石排镇', '441900104000', '441900000000');
INSERT INTO country  VALUES ('3291', '企石镇', '441900105000', '441900000000');
INSERT INTO country  VALUES ('3292', '横沥镇', '441900106000', '441900000000');
INSERT INTO country  VALUES ('3293', '桥头镇', '441900107000', '441900000000');
INSERT INTO country  VALUES ('3294', '谢岗镇', '441900108000', '441900000000');
INSERT INTO country  VALUES ('3295', '东坑镇', '441900109000', '441900000000');
INSERT INTO country  VALUES ('3296', '常平镇', '441900110000', '441900000000');
INSERT INTO country  VALUES ('3297', '寮步镇', '441900111000', '441900000000');
INSERT INTO country  VALUES ('3298', '樟木头镇', '441900112000', '441900000000');
INSERT INTO country  VALUES ('3299', '大朗镇', '441900113000', '441900000000');
INSERT INTO country  VALUES ('3300', '黄江镇', '441900114000', '441900000000');
INSERT INTO country  VALUES ('3301', '清溪镇', '441900115000', '441900000000');
INSERT INTO country  VALUES ('3302', '塘厦镇', '441900116000', '441900000000');
INSERT INTO country  VALUES ('3303', '凤岗镇', '441900117000', '441900000000');
INSERT INTO country  VALUES ('3304', '大岭山镇', '441900118000', '441900000000');
INSERT INTO country  VALUES ('3305', '长安镇', '441900119000', '441900000000');
INSERT INTO country  VALUES ('3306', '虎门镇', '441900121000', '441900000000');
INSERT INTO country  VALUES ('3307', '厚街镇', '441900122000', '441900000000');
INSERT INTO country  VALUES ('3308', '沙田镇', '441900123000', '441900000000');
INSERT INTO country  VALUES ('3309', '道滘镇', '441900124000', '441900000000');
INSERT INTO country  VALUES ('3310', '洪梅镇', '441900125000', '441900000000');
INSERT INTO country  VALUES ('3311', '麻涌镇', '441900126000', '441900000000');
INSERT INTO country  VALUES ('3312', '望牛墩镇', '441900127000', '441900000000');
INSERT INTO country  VALUES ('3313', '中堂镇', '441900128000', '441900000000');
INSERT INTO country  VALUES ('3314', '高埗镇', '441900129000', '441900000000');
INSERT INTO country  VALUES ('3315', '松山湖管委会', '441900401000', '441900000000');
INSERT INTO country  VALUES ('3316', '东莞港', '441900402000', '441900000000');
INSERT INTO country  VALUES ('3317', '东莞生态园', '441900403000', '441900000000');
INSERT INTO country  VALUES ('3318', '石岐区街道办事处', '442000001000', '442000000000');
INSERT INTO country  VALUES ('3319', '东区街道办事处', '442000002000', '442000000000');
INSERT INTO country  VALUES ('3320', '火炬开发区街道办事处', '442000003000', '442000000000');
INSERT INTO country  VALUES ('3321', '西区街道办事处', '442000004000', '442000000000');
INSERT INTO country  VALUES ('3322', '南区街道办事处', '442000005000', '442000000000');
INSERT INTO country  VALUES ('3323', '五桂山街道办事处', '442000006000', '442000000000');
INSERT INTO country  VALUES ('3324', '小榄镇', '442000100000', '442000000000');
INSERT INTO country  VALUES ('3325', '黄圃镇', '442000101000', '442000000000');
INSERT INTO country  VALUES ('3326', '民众镇', '442000102000', '442000000000');
INSERT INTO country  VALUES ('3327', '东凤镇', '442000103000', '442000000000');
INSERT INTO country  VALUES ('3328', '东升镇', '442000104000', '442000000000');
INSERT INTO country  VALUES ('3329', '古镇镇', '442000105000', '442000000000');
INSERT INTO country  VALUES ('3330', '沙溪镇', '442000106000', '442000000000');
INSERT INTO country  VALUES ('3331', '坦洲镇', '442000107000', '442000000000');
INSERT INTO country  VALUES ('3332', '港口镇', '442000108000', '442000000000');
INSERT INTO country  VALUES ('3333', '三角镇', '442000109000', '442000000000');
INSERT INTO country  VALUES ('3334', '横栏镇', '442000110000', '442000000000');
INSERT INTO country  VALUES ('3335', '南头镇', '442000111000', '442000000000');
INSERT INTO country  VALUES ('3336', '阜沙镇', '442000112000', '442000000000');
INSERT INTO country  VALUES ('3337', '南朗镇', '442000113000', '442000000000');
INSERT INTO country  VALUES ('3338', '三乡镇', '442000114000', '442000000000');
INSERT INTO country  VALUES ('3339', '板芙镇', '442000115000', '442000000000');
INSERT INTO country  VALUES ('3340', '大涌镇', '442000116000', '442000000000');
INSERT INTO country  VALUES ('3341', '神湾镇', '442000117000', '442000000000');
INSERT INTO country  VALUES ('3342', '那大镇', '460400100000', '460400000000');
INSERT INTO country  VALUES ('3343', '和庆镇', '460400101000', '460400000000');
INSERT INTO country  VALUES ('3344', '南丰镇', '460400102000', '460400000000');
INSERT INTO country  VALUES ('3345', '大成镇', '460400103000', '460400000000');
INSERT INTO country  VALUES ('3346', '雅星镇', '460400104000', '460400000000');
INSERT INTO country  VALUES ('3347', '兰洋镇', '460400105000', '460400000000');
INSERT INTO country  VALUES ('3348', '光村镇', '460400106000', '460400000000');
INSERT INTO country  VALUES ('3349', '木棠镇', '460400107000', '460400000000');
INSERT INTO country  VALUES ('3350', '海头镇', '460400108000', '460400000000');
INSERT INTO country  VALUES ('3351', '峨蔓镇', '460400109000', '460400000000');
INSERT INTO country  VALUES ('3352', '王五镇', '460400111000', '460400000000');
INSERT INTO country  VALUES ('3353', '白马井镇', '460400112000', '460400000000');
INSERT INTO country  VALUES ('3354', '中和镇', '460400113000', '460400000000');
INSERT INTO country  VALUES ('3355', '排浦镇', '460400114000', '460400000000');
INSERT INTO country  VALUES ('3356', '东成镇', '460400115000', '460400000000');
INSERT INTO country  VALUES ('3357', '新州镇', '460400116000', '460400000000');
INSERT INTO country  VALUES ('3358', '洋浦经济开发区', '460400499000', '460400000000');
INSERT INTO country  VALUES ('3359', '华南热作学院', '460400500000', '460400000000');

**Comment by zhyq0826** [comment]
@dongliang0201 ，这部分数据以及包含在 town.sql 中，见 https://github.com/wecatch/china_regions#2019417 ，多写反馈。
