### ISSUE TITLE
缺失数据

### ISSUE THREAD

**Issue by relax-admin** [wecatch/china_regions#21]
county里没有county_id=441900000000的数据 （东莞市），但是在town表里存在county_id=441900000000 的数据。

原因是东莞市没有county，从第二级（city）直接到第四级（town）了

方案：是否需要插入一条数据在county？
```sql
INSERT county VALUES(1,'东莞市','441900000000','441900000000')
```

信息：
```sql
SELECT * FROM town a
left JOIN county b ON  a.county_id = b.county_id
WHERE b.NAME IS null

SELECT * FROM city
WHERE city_id ='441900000000'
```

**Comment by relax-admin** [comment]
东莞市 没有第3级，发现city有这一条数据，所以 county是否需要新增一条数据city_id ='441900000000'的数据呢

SELECT * FROM city
WHERE city_id ='441900000000'

**Comment by zhyq0826** [comment]
@relax-admin 这部分数据并不是缺失了，见 https://github.com/wecatch/china_regions/blob/master/src/special_city.json ，由于这些城市没有 country，直接就是 town，你可以根据自己的情况特殊处理，比如选择这类城市，直接跳到 town 去处理，见 https://github.com/wecatch/china_regions/issues/17

**Comment by relax-admin** [comment]
@zhyq0826 ok ,明白
