### ISSUE TITLE
为什么在 city.json 里面会有 name 为 “省直辖县级行政区划” 的 object，是否要去掉？

### ISSUE THREAD

**Issue by yuduxyz** [wecatch/china_regions#3]

**Comment by zhyq0826** [comment]
@yuduxyz 参考国标 http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html 以及百度百科的介绍 http://baike.baidu.com/item/%E7%9C%81%E7%9B%B4%E8%BE%96%E5%8E%BF%E7%BA%A7%E8%A1%8C%E6%94%BF%E5%8D%95%E4%BD%8D?sefr=enterbtn , `省直辖县级行政区划` 是一种行政单位，和市相似，这个单位下面的县直接归于省管理。

**Comment by yuduxyz** [comment]
啊，懂了，多谢解答~
